### ISSUE TITLE
Make individual issues for lessons we learned in Athens

### ISSUE THREAD

**Issue by mushon** [mushon/Turing-Normalizing-Machine#23]
- [ ] - color correction- colors too desaturated 
- [ ] - ✖️should appear prior to ✔️
- [ ] - account for small people (children)
- [ ] - investigate how pointing worked in 0.1 (maybe calibrate by each user's individual pointing)
- [ ] - make left hand work too (lefties are also normal)
- [ ] - soften elastic layout, experiment with delayed response 
- [ ] - implement the rest of the animation
- [ ] - implement with Kinect camera
- [x] - install on a Mac. Test w Mac Mini
- [ ] - shuffle the 4 panels to not always show the new one on the top left and the random one on the bottom right
- [ ] - create a setup screen for calibrating based on hand gestures
- [ ] - add subtle sound effects

**Comment by eranws** [comment]
created separate issues
