### ISSUE TITLE
Write Script to remove the placeholder video and initialize the JSON file

### ISSUE THREAD

**Issue by mushon** [mushon/Turing-Normalizing-Machine#24]
To avoid the persistence of the ``test1.oni`` record in the database, we need a script that would rewrite the ``dataset.json`` file and initialize the installation on the basis of the new local records.

**Comment by eranws** [comment]
Already closed in 35b6d709 :)

**Comment by mushon** [comment]
Awesome thanks!
Did you get to update the zip file too?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by eranws** [comment]
'fcourse

**Comment by mushon** [comment]
You rule!
